-- 월별 주문수 
SELECT T.DATE, COUNT(T.DATE) AS COUNT
FROM (
         SELECT DATE_FORMAT(TOS.REGISTRATION_DT, '2022') AS DATE, REGISTER_SEQ FROM TB_ORDER TOS
         WHERE TOS.REGISTRATION_DT BETWEEN '2022-01-16 00:00:00' AND '2022-02-15 23:59:59'
         GROUP BY DATE_FORMAT(TOS.REGISTRATION_DT, '%Y-%m'), REGISTER_SEQ
     ) T
GROUP BY T.DATE