spring:
  profiles:
    active: local
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://10.80.1.84:3306/nikednp?autoReconnection=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: 'mariadb'
  #h2:
  #  console:
  #    enabled: true
  #datasource:
  #  driverClassName: org.h2.Driver
  #  url: jdbc:h2:mem:testdb
  #  username: sa
  #  password:

  jpa:
    show-sql: true
    properties:
      hibernate.formal_sql: true
      hibernate.use_sql_comments: true
    generate-ddl: false
    hibernate:
      ddl-auto: none