spring:
  profiles: nikeprod
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://nike-prod-db.c9c2dtiz524o.ap-northeast-2.rds.amazonaws.com:3306/nikedb?autoReconnection=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowMultiQueries=true
  hikari:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    minimumIdle: 200
    maximumPoolSize: 200
    poolName: SpringBootJPAHikariCP
    idleTimeout: 10000
    connection-timeout: 10000
    validation-timeout: 10000
    maxLifetime: 580000
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      useLocalTransactionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  jpa:
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show-sql: false
        SQL: info
        format_sql: false
        use_sql_comments: false
        type:
          descriptor:
            sql: info
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    output:
      ansi:
        enabled: always
  redis:
    host: nike-prod-redis.f5zylx.ng.0001.apn2.cache.amazonaws.com
    port: 6379
    cache:
      redis:
        cache-null-values: false
        use-key-prefix: true
      type: redis
    userSessionTime: 30

logging:
  config: classpath:logback-nikeprod.xml

server:
  domain: https://www.nikespace.co.kr
  port: 8080

## 시큐리티 url/ ip 체크 flag
security:
  auth:
    url: true
    ip : false

## Custom 설정
nike:
  ## Link 관련 설정
  url:
    pc:
      domain: 'https://www.nikespace.co.kr'
    mobile:
      domain: 'https://m.nikespace.co.kr'
    login: '/login'
    password: '/password-set'
  ## File 관련 설정
  file:
    root: '/home/ec2-user/file_temp'
    imageMagick: '/usr/bin'
    imageMagickCommand: 'convert'
    ffmpeg: '/usr/bin'
    ffmpegCommand: 'ffmpeg'

## AWS
cloud:
  aws:
    distributionDomain: 'upload.nikespace.co.kr'
    privateKeyFilePath: '/home/ec2-user/der/nikecdn.der'
    s3:
      bucket: 'nike-prod-bucket-dnp'
      editor: 'nike-prod-resource-bucket-dnp'
    stack:
      auto:  false