spring:
  profiles: nikeprod
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nikedb?autoReconnection=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: nikemanager
    password: 'emotion!@'
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    output:
      ansi:
        enabled: always
  redis:
    host: 10.80.1.212
    port: 6379
    cache:
      redis:
        cache-null-values: false
        use-key-prefix: true
      type: redis
    userSessionTime: 30

logging:
  config: classpath:logback-nikeprod.xml

server:
  domain: http://localhost
  port: 8080

## 시큐리티 url/ ip 체크 flag
security:
  auth:
    url: true
    ip : false

## Custom 설정
nike:
  ## Link 관련 설정
  url:
    pc:
      domain: 'http://localhost:8081'
    mobile:
      domain: 'http://localhost:8082'
    login: '/login'
    password: '/password-set'
  ## File 관련 설정
  file:
    root: '/home/emotion/file_temp'
    imageMagick: '/usr/bin'
    imageMagickCommand: 'convert'
    ffmpeg: '/usr/bin'
    ffmpegCommand: 'ffmpeg'

## AWS
cloud:
  aws:
    distributionDomain: 'upload.nikespace.co.kr'
    privateKeyFilePath: '/home/ec2-user/der/nikecdn.der'
    credentials:
      accessKey: 'AKIA4FO4XQUFNEBRAZU4'
      secretKey: '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'
    s3:
      bucket: 'nike-prod-bucket-dnp'
      editor: 'nike-prod-resource-bucket-dnp'
    region:
      static: 'ap-northeast-2'
    stack:
      auto:  false