spring:
  profiles:
    active: local
  mvc:
    favicon:
      enabled: false
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        #show-sql: true
        SQL: debug
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: info
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#시큐리티 url/ ip 체크 flag
security:
  auth:
    url: false
    ip : false
