spring:
  profiles: nikeprod
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://nike-prod-db.c9c2dtiz524o.ap-northeast-2.rds.amazonaws.com:3306/nikedb?autoReconnection=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: nikemanager
    password: 'emotion!@'
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    output:
      ansi:
        enabled: always
  redis:
    host: nike-prod-redis.f5zylx.ng.0001.apn2.cache.amazonaws.com
    port: 6379
    cache:
      redis:
        cache-null-values: false
        use-key-prefix: true
      type: redis
    userSessionTime: 30

logging:
  config: classpath:logback-nikeprod.xml

server:
  domain: http://localhost
  port: 8080

## 시큐리티 url/ ip 체크 flag
security:
  auth:
    url: false
    ip : false

#임시경로
nike:
  file:
    root: '/home/emotion/file_temp'
    imageMagick: '/usr/bin'
    imageMagickCommand: 'convert'
    ffmpeg: '/usr/bin'
    ffmpegCommand: 'ffmpeg'
