spring:
  profiles: prod
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    output:
      ansi:
        enabled: always
  redis:
    host: 10.80.1.212
    port: 6379
    #password: 2motion1!!
    cache:
      redis:
        cache-null-values: false
        use-key-prefix: true
      type: redis
    userSessionTime: 30

logging:
  config: classpath:logback-prod.xml

server:
  domain: http://localhost
  port: 8080