spring:
  profiles:
    active: local
  mvc:
    favicon:
      enabled: false
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show-sql: true
        SQL: debug
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: info
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  redis:
    userSessionTime: 30

## 시큐리티 url/ ip 체크 flag
security:
  auth:
    url: true
    ip : false

## Custom 설정
nike:
  ## email 계정
  email:
    auth:
      id: 'admin@nikespace.co.kr'
      pw: '2motion12!@'
    send:
      from: 'admin@nikespace.co.kr'

## AWS 설정
cloud:
  aws:
    keyPairId: 'APKAJNYFE4SZH6RSWVMA'
