spring:
  profiles: nikedev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://nike-test-db.c9c2dtiz524o.ap-northeast-2.rds.amazonaws.com:3306/nikedb?autoReconnection=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: nikemanager
    password: 'emotion!@'
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    output:
      ansi:
        enabled: always
  redis:
    host: nike-test-redis-a.f5zylx.ng.0001.apn2.cache.amazonaws.com
    port: 6379
    cache:
      redis:
        cache-null-values: false
        use-key-prefix: true
      type: redis
    userSessionTime: 30

logging:
  config: classpath:logback-nikedev.xml

server:
  domain: https://devwww.nikespace.co.kr
  port: 8080

## 시큐리티 url/ ip 체크 flag
security:
  auth:
    url: true
    ip : false

## Custom 설정
nike:
  ## Link 관련 설정
  url:
    pc:
      domain: 'https://devwww.nikespace.co.kr'
    mobile:
      domain: 'https://devm.nikespace.co.kr'
    login: '/login'
    password: '/password-set'
  ## File 관련 설정
  file:
    root: '/home/ec2-user/file_temp'
    imageMagick: '/usr/bin'
    imageMagickCommand: 'convert'
    ffmpeg: '/usr/bin'
    ffmpegCommand: 'ffmpeg'
    editorUrl: 'https://nike-test-resource-bucket-dnp.s3.ap-northeast-2.amazonaws.com'

## AWS
cloud:
  aws:
    distributionDomain: 'devupload.nikespace.co.kr'
    privateKeyFilePath: '/home/ec2-user/der/nikecdn.der'
    s3:
      bucket: 'nike-test-bucket-dnp'
      editor: 'nike-test-resource-bucket-dnp'
    stack:
      auto:  false