spring:
  profiles: nikedev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://nike-test-db.c9c2dtiz524o.ap-northeast-2.rds.amazonaws.com:3306/nikedb?autoReconnection=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: nikemanager
    password: 'emotion!@'
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    output:
      ansi:
        enabled: always
  redis:
    host: nike-test-redis-a.f5zylx.ng.0001.apn2.cache.amazonaws.com
    port: 6379
    #password: 2motion1!!
    cache:
      redis:
        cache-null-values: false
        use-key-prefix: true
      type: redis
    userSessionTime: 30

logging:
  config: classpath:logback-nikedev.xml

server:
  domain: http://localhost
  port: 8080

## 시큐리티 url/ ip 체크 flag
security:
  auth:
    url: false
    ip : false

#임시경로
nike:
  file:
    root: '/home/emotion/file_temp'
    imageMagick: '/usr/bin'
    imageMagickCommand: 'convert'
    ffmpeg: '/usr/bin'
    ffmpegCommand: 'ffmpeg'

## AWS
cloud:
  aws:
    distributionDomain: 'd3a4mwwf905xos.cloudfront.net'
    privateKeyFilePath: '/home/ec2-user/nikecdn.der'
    credentials:
      accessKey: 'AKIA4FO4XQUFNEBRAZU4'
      secretKey: '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'
    s3:
      bucket: 'nike-test-bucket-dnp'
    region:
      static: 'ap-northeast-2'
    stack:
      auto:  false

