spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nikedb?autoReconnection=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    #driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:log4jdbc:mariadb://localhost:3306/nikedb?autoReconnection=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: nikemanager
    password: 'emotion!@'
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    output:
      ansi:
        enabled: always
  redis:
    host: 10.80.1.212
    port: 6379
    cache:
      redis:
        cache-null-values: false
        use-key-prefix: true
      type: redis
    userSessionTime: 30

logging:
  config: classpath:logback-dev.xml

server:
  domain: http://localhost
  port: 8080

## 시큐리티 url/ ip 체크 flag
security:
  auth:
    url: false
    ip : false

## 임시경로
nike:
  file:
    root: '/home/emotion/file_temp'
    imageMagick: '/usr/bin'
    imageMagickCommand: 'convert'
    ffmpeg: '/usr/bin'
    ffmpegCommand: 'ffmpeg'
    editorUrl: 'https://nike-test-resource-bucket-dnp.s3.ap-northeast-2.amazonaws.com'

## AWS
cloud:
  aws:
    distributionDomain: 'devresource.nikespace.co.kr'
    privateKeyFilePath: '/home/emotion/tomcat8/der/nikecdn.der'
    credentials:
      accessKey: 'AKIA4FO4XQUFNEBRAZU4'
      secretKey: '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'
    s3:
      bucket: 'nike-test-bucket-dnp'
      editor: 'nike-test-resource-bucket-dnp'
    region:
      static: 'ap-northeast-2'
    stack:
      auto:  false