spring:
  profiles:
    active: local
  mvc:
    favicon:
      enabled: false
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        #show-sql: true
        SQL: debug
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: info
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB



## 시큐리티 url/ ip 체크 flag
security:
  auth:
    url: true
    ip : false

## email 계정
nike:
  email:
    auth:
      id: "cokeplay.emotion@emotion.co.kr"
      pw: "5Rzz*w#,Kc%9W7s"
    send:
      from: "cokeplay.emotion@emotion.co.kr"
  #임시 경로
  file:
    root: '/home/file'
    imageMagick: '/imageTool'
