-- ASSET_게시물별 특정파트너 다운로드 수
    -- 기간안에 등록된 게시물
SELECT TC.FOLDER_NAME,
       SUM(CASE WHEN T.AUTH_SEQ = 21 OR T.UPPER_AUTH_SEQ = 21 OR T.AUTH_SEQ = 95 OR T.AUTH_SEQ = 96 OR T.AUTH_SEQ = 97 OR T.AUTH_SEQ = 98 THEN 1 ELSE 0 END ) 'DAEYEON',
       SUM(CASE WHEN T.AUTH_SEQ = 22 OR T.UPPER_AUTH_SEQ = 22 OR T.AUTH_SEQ = 99 OR T.AUTH_SEQ = 100 OR T.AUTH_SEQ = 101 OR T.AUTH_SEQ = 102 THEN 1 ELSE 0 END ) 'EUNGWANG',
       SUM(CASE WHEN T.AUTH_SEQ = 23 OR T.UPPER_AUTH_SEQ = 23 OR T.AUTH_SEQ = 103 OR T.AUTH_SEQ = 104 OR T.AUTH_SEQ = 105 THEN 1 ELSE 0 END ) 'WINWIN SPORTS',
       SUM(CASE WHEN T.AUTH_SEQ = 24 OR T.UPPER_AUTH_SEQ = 24 OR T.AUTH_SEQ = 106 OR T.AUTH_SEQ = 107 THEN 1 ELSE 0 END ) 'SHOE LAND',
       SUM(CASE WHEN T.AUTH_SEQ = 25 OR T.UPPER_AUTH_SEQ = 25 OR T.AUTH_SEQ = 108 OR T.AUTH_SEQ = 109 THEN 1 ELSE 0 END ) 'HD',
       SUM(CASE WHEN T.AUTH_SEQ = 26 OR T.UPPER_AUTH_SEQ = 26 OR T.AUTH_SEQ = 110 OR T.AUTH_SEQ = 111 THEN 1 ELSE 0 END ) 'DAESAN SPORTS',
       SUM(CASE WHEN T.AUTH_SEQ = 27 OR T.UPPER_AUTH_SEQ = 27 OR T.AUTH_SEQ = 112 OR T.AUTH_SEQ = 113 THEN 1 ELSE 0 END ) 'SMH SPORTS KOREA',
       SUM(CASE WHEN T.AUTH_SEQ = 28 OR T.UPPER_AUTH_SEQ = 28 OR T.AUTH_SEQ = 114 OR T.AUTH_SEQ = 115 THEN 1 ELSE 0 END ) 'KU & HOOPS'
FROM TB_CONTENTS TC
LEFT JOIN (
    SELECT TCF.CONTENTS_SEQ, TDL.REGISTRATION_DT, TA.AUTH_SEQ, TA.UPPER_AUTH_SEQ
    FROM TB_DOWNLOAD_LOG TDL
    INNER JOIN TB_CONTENTS_FILE TCF
    ON TDL.FILE_SEQ = TCF.CONTENTS_FILE_SEQ
    INNER JOIN TB_USER TU
    ON TDL.REGISTER_SEQ = TU.USER_SEQ
    INNER JOIN TB_USER_AUTH TUA
    ON TU.USER_SEQ = TUA.USER_SEQ
    INNER JOIN TB_AUTH TA
    ON TUA.AUTH_SEQ = TA.AUTH_SEQ
    WHERE TDL.DOWNLOAD_TYPE = 'CONTENTS'
    AND TDL.REGISTRATION_DT BETWEEN '2021-09-16 00:00:00' AND '2021-10-15 23:59:59'
) T
ON T.CONTENTS_SEQ = TC.CONTENTS_SEQ
WHERE TC.TOP_MENU_CODE = 'ASSET'
AND TC.REGISTRATION_DT BETWEEN '2021-09-16 00:00:00' AND '2021-10-15 23:59:59'
GROUP BY TC.CONTENTS_SEQ
;