-- 그룹수
-- 기간 : 최초 등록일 ~
SELECT AUTH_DEPTH, COUNT(AUTH_DEPTH)
FROM TB_AUTH
WHERE REGISTRATION_DT BETWEEN '2020-08-01 00:00:00' AND '2021-12-15 23:59:59'
  AND USE_YN = 'Y'
GROUP BY AUTH_DEPTH;



-- 계정수
SELECT TA.AUTH_DEPTH, COUNT(TA.AUTH_DEPTH)
FROM TB_USER TU
LEFT JOIN TB_USER_AUTH TUA
ON TU.USER_SEQ = TUA.USER_SEQ
LEFT JOIN TB_AUTH TA
on TA.AUTH_SEQ = TUA.AUTH_SEQ
WHERE TU.REGISTRATION_DT BETWEEN '2020-08-01 00:00:00' AND '2021-11-15 23:59:59'
AND TU.USER_STATUS_CODE = 'NORMAL'
GROUP BY TA.AUTH_DEPTH
;


-- 그룹수/계정수
SELECT TG.*, TA.ACCOUNT_COUNT
FROM (
         SELECT AUTH_DEPTH, COUNT(AUTH_DEPTH)
         FROM TB_AUTH
         WHERE REGISTRATION_DT BETWEEN '2020-08-01 00:00:00' AND '2021-12-15 23:59:59'
           AND USE_YN = 'Y'
         GROUP BY AUTH_DEPTH
     ) TG
         LEFT OUTER JOIN (
    SELECT TA.AUTH_DEPTH, COUNT(TA.AUTH_DEPTH) AS ACCOUNT_COUNT
    FROM TB_USER TU
             LEFT JOIN TB_USER_AUTH TUA
                       ON TU.USER_SEQ = TUA.USER_SEQ
             LEFT JOIN TB_AUTH TA
                       on TA.AUTH_SEQ = TUA.AUTH_SEQ
    WHERE TU.REGISTRATION_DT BETWEEN '2020-08-01 00:00:00' AND '2021-12-15 23:59:59'
      AND TU.USER_STATUS_CODE = 'NORMAL'
    GROUP BY TA.AUTH_DEPTH
) TA
ON TG.AUTH_DEPTH = TA.AUTH_DEPTH
;