-- 캠페인별 상세보기 수
SELECT TC.TOP_MENU_CODE, TC.MENU_CODE, SUM(TC.READ_COUNT) AS SUM
FROM TB_CONTENTS TC
GROUP BY TC.TOP_MENU_CODE, TC.MENU_CODE
;


SELECT TOP_MENU_CODE,MENU_CODE, SUM(READ_COUNT) AS COUNT
FROM TB_CONTENTS
WHERE TOP_MENU_CODE = 'ASSET'

SELECT *
FROM TB_USER_ACTION_LOG
WHERE METHOD_SIGNATURE = 'findContents'
  AND METHOD_TYPE_NAME = 'GET'
#   AND URL LIKE '%TOOLKIT%'
#   AND URL LIKE '%TOOLKIT%' AND URL LIKE '%VMS%'
  AND REGISTRATION_DT BETWEEN '2020-09-24 00:00:00' AND '2020-11-30 23:59:59'
ORDER BY REGISTRATION_DT ASC

SELECT
    CATEGORY, COUNT(CATEGORY) AS COUNT
FROM (
    SELECT CASE
        WHEN URL LIKE '%ASSET%' AND URL LIKE '%SP%' THEN 'ASSET_SP'
        WHEN URL LIKE '%ASSET%' AND URL LIKE '%SU%' THEN 'ASSET_SU'
        WHEN URL LIKE '%ASSET%' AND URL LIKE '%FA%' THEN 'ASSET_FA'
        WHEN URL LIKE '%ASSET%' AND URL LIKE '%HO%' THEN 'ASSET_HO'

        WHEN URL LIKE '%FOUNDATION%' AND URL LIKE '%VMS%' THEN 'FOUNDATION_VMS'
        WHEN URL LIKE '%FOUNDATION%' AND URL LIKE '%EKIN%' THEN 'FOUNDATION_EKIN'
        WHEN URL LIKE '%FOUNDATION%' AND URL LIKE '%DIGITAL%' THEN 'FOUNDATION_DIGITAL'
        WHEN URL LIKE '%FOUNDATION%' AND URL LIKE '%RB%' THEN 'FOUNDATION_RB'

        WHEN URL LIKE '%TOOLKIT%' AND URL LIKE '%VMS%' THEN 'TOOLKIT_VMS'
        WHEN URL LIKE '%TOOLKIT%' AND URL LIKE '%EKIN%' THEN 'TOOLKIT_EKIN'
        WHEN URL LIKE '%TOOLKIT%' AND URL LIKE '%SOCIAL%' THEN 'TOOLKIT_SOCIAL'
        WHEN URL LIKE '%TOOLKIT%' AND URL LIKE '%RB%' THEN 'TOOLKIT_RB'
        END AS CATEGORY
    FROM TB_USER_ACTION_LOG
    WHERE METHOD_SIGNATURE = 'findContents'
    AND METHOD_TYPE_NAME = 'GET'
    AND REGISTRATION_DT BETWEEN '2020-01-01 00:00:00' AND '2020-11-30 23:59:59'
) A
GROUP BY CATEGORY;


SELECT
    CATEGORY, COUNT(CATEGORY) AS COUNT
FROM (
         SELECT *
         FROM TB_USER_ACTION_LOG
         WHERE METHOD_SIGNATURE = 'findContents'
           AND METHOD_TYPE_NAME = 'GET'
           AND  (URL LIKE '%FOUNDATION%' AND URL LIKE '%EKIN%')
           AND REGISTRATION_DT BETWEEN '2020-09-24 00:00:00' AND '2020-12-02 23:59:59'
     ) A
GROUP BY CATEGORY;