-- 다운로드 수
SELECT TA.AUTH_NAME, IFNULL(S.COUNT, 0) AS COUNT
FROM TB_AUTH TA
LEFT JOIN
(
    SELECT T.AUTH_SEQ, COUNT(T.AUTH_SEQ) AS COUNT
    FROM (
        SELECT 	CASE
            WHEN TA.AUTH_DEPTH = 1 THEN TA.AUTH_SEQ
            WHEN TA.AUTH_DEPTH = 2 THEN TA.AUTH_SEQ
            WHEN TA.AUTH_DEPTH = 3 THEN UTA.AUTH_SEQ
        END AS AUTH_SEQ
        FROM TB_DOWNLOAD_LOG TDL
        INNER JOIN TB_USER TU
        ON TDL.REGISTER_SEQ = TU.USER_SEQ
        INNER JOIN TB_USER_AUTH TUA
        ON TU.USER_SEQ = TUA.USER_SEQ
        INNER JOIN TB_AUTH TA
        ON TUA.AUTH_SEQ = TA.AUTH_SEQ
        LEFT JOIN TB_AUTH UTA
        ON TA.UPPER_AUTH_SEQ = UTA.AUTH_SEQ
        LEFT JOIN TB_CONTENTS_FILE TCF
        ON TDL.FILE_SEQ = TCF.CONTENTS_FILE_SEQ
        LEFT JOIN TB_CONTENTS TC
        ON TCF.CONTENTS_SEQ = TC.CONTENTS_SEQ
        WHERE TDL.DOWNLOAD_TYPE = 'CONTENTS'
      AND TC.TOP_MENU_CODE = 'TOOLKIT'
      AND TDL.REGISTRATION_DT BETWEEN '2020-01-01 00:00:00' AND '2020-12-31 23:59:59'
      AND TC.DEVICE = 'PC'
        # AND TUAL.DEVICE = 'MO'
    ) T
    GROUP BY T.AUTH_SEQ
) S
ON TA.AUTH_SEQ = S.AUTH_SEQ
# WHERE TA.AUTH_DEPTH = 1
WHERE TA.AUTH_DEPTH = 2
ORDER BY TA.AUTH_SEQ;
