-- 월별 순 방문수 
SELECT DT.DATE AS DATE
		, IFNULL(RESULT.COUNT , 0) AS COUNT 
FROM (
	SELECT CONCAT('2020-', A) AS DATE
	FROM (
		SELECT '01' AS A
		UNION ALL SELECT '02' 
		UNION ALL SELECT '03' 
		UNION ALL SELECT '04' 
		UNION ALL SELECT '05' 
		UNION ALL SELECT '06' 
		UNION ALL SELECT '07' 
		UNION ALL SELECT '08' 
		UNION ALL SELECT '09'
		UNION ALL SELECT '10'
		UNION ALL SELECT '11'
		UNION ALL SELECT '12'
	) AS A 
) DT
LEFT JOIN (
	SELECT USER.DATE, COUNT(USER.DATE) AS COUNT
	FROM (
		SELECT DATE_FORMAT(TULL.LOGIN_DT, "%Y-%m") AS DATE
		FROM TB_USER_LOGIN_LOG TULL
		WHERE TULL.LOGIN_DT BETWEEN '2020-01-01 00:00:00' AND '2020-11-12 23:59:59'
		GROUP BY DATE_FORMAT(TULL.LOGIN_DT, "%Y-%m-%d"), TULL.USER_SEQ
	) USER
	GROUP BY USER.DATE
) AS RESULT
ON DT.DATE = RESULT.DATE
;
