-- A/T/F 게시물별 다운로드 수
SELECT COUNT(TDL.DOWNLOAD_LOG_SEQ)
FROM TB_DOWNLOAD_LOG TDL
WHERE TDL.DOWNLOAD_TYPE = 'CONTENTS'
AND TDL.REGISTRATION_DT BETWEEN '2020-11-13 11:55:33' AND '2020-11-30 23:59:59'

# 10월 1448
# 11월 814
#     2020-11-13 11:55:33   293




SELECT T.FOLDER_NAME, COUNT(T.FOLDER_NAME) AS COUNT
FROM (
    SELECT COUNT(TDL.DOWNLOAD_LOG_SEQ)
    FROM TB_DOWNLOAD_LOG TDL
    LEFT JOIN TB_CONTENTS_FILE TCF
    ON TDL.FILE_SEQ = TCF.CONTENTS_FILE_SEQ
    LEFT JOIN TB_CONTENTS TC
    ON TCF.CONTENTS_SEQ = TC.CONTENTS_SEQ
    WHERE TDL.DOWNLOAD_TYPE = 'CONTENTS'
#     AND TC.TOP_MENU_CODE = 'ASSET'
    # AND TC.TOP_MENU_CODE = 'TOOLKIT'
    # AND TC.TOP_MENU_CODE = 'FOUNDATION'
    AND TDL.REGISTRATION_DT BETWEEN '2020-11-01 00:00:00' AND '2020-11-30 23:59:59'
    ORDER BY TC.CONTENTS_SEQ
#     18
 ) T
GROUP BY T.FOLDER_NAME;


# SELECT TC.CONTENTS_SEQ, TC.FOLDER_NAME, COUNT(TDL.DOWNLOAD_LOG_SEQ)
# , CASE
#       WHEN TDL.REGISTRATION_DT BETWEEN '2020-10-01 00:00:00' AND '2020-10-31 23:59:59' THEN COUNT(TDL.DOWNLOAD_LOG_SEQ)
#       ELSE 0
#     END AS TEM
# , CASE
#     WHEN TDL.REGISTRATION_DT BETWEEN '2020-11-01 00:00:00' AND '2020-11-30 23:59:59' THEN COUNT(TDL.DOWNLOAD_LOG_SEQ)
#     ELSE 0
#     END AS ELE


# 11월 다운로드 로그 : 814

-- A/T/F 게시물별 다운로드 수
SELECT TC.CONTENTS_SEQ, TC.FOLDER_NAME, TDL.DOWNLOAD_LOG_SEQ
FROM TB_CONTENTS TC
LEFT JOIN TB_CONTENTS_FILE TCF
ON TC.CONTENTS_SEQ = TCF.CONTENTS_SEQ
LEFT JOIN  TB_DOWNLOAD_LOG TDL
ON TDL.FILE_SEQ = TCF.CONTENTS_FILE_SEQ
AND TDL.DOWNLOAD_TYPE = 'CONTENTS'
AND TDL.REGISTRATION_DT BETWEEN '2020-11-13 11:55:33' AND '2020-11-30 23:59:59'
# WHERE TC.TOP_MENU_CODE = 'ASSET'
# WHERE TC.TOP_MENU_CODE = 'TOOLKIT'
# WHERE TC.TOP_MENU_CODE = 'FOUNDATION'
# GROUP BY TC.CONTENTS_SEQ
# ORDER BY TC.CONTENTS_SEQ;

SELECT TC.CONTENTS_SEQ, TC.FOLDER_NAME
#      , COUNT(D.DOWNLOAD_COUNT) AS ALL_COUNT
     , IFNULL(COUNT(D.TEN), 0) AS TEN
     , IFNULL(COUNT(D.ELE), 0) AS ELE
# SELECT *
FROM TB_CONTENTS TC
LEFT JOIN (
#     SELECT TCF.CONTENTS_SEQ, TDL.FILE_SEQ
    SELECT TCF.CONTENTS_SEQ, TDL.FILE_SEQ, IFNULL(COUNT(TDL.DOWNLOAD_LOG_SEQ), 0) AS DOWNLOAD_COUNT
    , CASE
          WHEN TDL.REGISTRATION_DT BETWEEN '2020-10-01 00:00:00' AND '2020-10-31 23:59:59' THEN COUNT(TDL.DOWNLOAD_LOG_SEQ)
        END AS TEN
    , CASE
        WHEN TDL.REGISTRATION_DT BETWEEN '2020-11-01 00:00:00' AND '2020-11-30 23:59:59' THEN COUNT(TDL.DOWNLOAD_LOG_SEQ)
        END AS ELE
    FROM TB_DOWNLOAD_LOG TDL
    LEFT JOIN TB_CONTENTS_FILE TCF
    ON TDL.FILE_SEQ = TCF.CONTENTS_FILE_SEQ
    WHERE TDL.DOWNLOAD_TYPE = 'CONTENTS'
#     AND TDL.REGISTRATION_DT BETWEEN '2020-10-01 00:00:00' AND '2020-11-30 23:59:59'
    GROUP BY TDL.FILE_SEQ
) D
ON TC.CONTENTS_SEQ = D.CONTENTS_SEQ
# WHERE TOP_MENU_CODE = 'ASSET'
WHERE TOP_MENU_CODE = 'TOOLKIT'
# WHERE TOP_MENU_CODE = 'FOUNDATION'
GROUP BY TC.CONTENTS_SEQ



SELECT TC.TOP_MENU_CODE, TC.FOLDER_NAME
FROM TB_CONTENTS_FILE TCF
LEFT JOIN TB_CONTENTS TC on TC.CONTENTS_SEQ = TCF.CONTENTS_SEQ
WHERE TCF.CONTENTS_FILE_SEQ = 9826

SELECT * FROM TB_CONTENTS_FILE
WHERE CONTENTS_FILE_SEQ = 9826


SELECT * FROM TB_USER_ACTION_LOG
WHERE METHOD_SIGNATURE = 'downloadLog'
  AND (REGISTRATION_DT BETWEEN '2020-11-13 00:00:00' AND '2020-11-13 23:59:59')
















SELECT * FROM TB_CONTENTS WHERE
                            TOP_MENU_CODE = 'FOUNDATION'


SELECT COUNT(*) FROM TB_DOWNLOAD_LOG TDL
WHERE TDL.DOWNLOAD_TYPE = 'CONTENTS'
AND TDL.REGISTRATION_DT BETWEEN '2020-01-01 00:00:00' AND '2020-11-30 23:59:59'

# 2262