-- 월별 평균 방문수 
SELECT DATE_FORMAT(USER.DATE, "%Y") AS DATE
		, SUM(USER.COUNT) AS SUM
		, COUNT(USER.DATE) AS COUNT
		, ROUND(AVG(USER.COUNT), 0) AS AVERAGE
FROM (
	SELECT TULL.LOGIN_DT AS DATE, COUNT(*) AS COUNT
	FROM TB_USER_LOGIN_LOG TULL
	WHERE TULL.LOGIN_DT BETWEEN '2020-01-01 00:00:00' AND '2020-12-31 23:59:59'
	AND TULL.DEVICE = 'PC'
	GROUP BY DATE_FORMAT(LOGIN_DT, "%Y-%m-%d") 
) USER
GROUP BY DATE_FORMAT(USER.DATE, "%Y")
;