SELECT TA.AUTH_NAME, IFNULL(S.COUNT, 0) AS COUNT
FROM TB_AUTH TA
LEFT JOIN
(
SELECT T.AUTH_SEQ, COUNT(T.AUTH_SEQ) AS COUNT
FROM (
SELECT 	CASE
			WHEN TA.AUTH_DEPTH = 1 THEN TA.AUTH_SEQ
			WHEN TA.AUTH_DEPTH = 2 THEN TA.AUTH_SEQ
			WHEN TA.AUTH_DEPTH = 3 THEN UTA.AUTH_SEQ
		END AS AUTH_SEQ
FROM TB_USER_ACTION_LOG TUAL
INNER JOIN TB_USER TU
ON TUAL.USER_SEQ = TU.USER_SEQ
INNER JOIN TB_USER_AUTH TUA
ON TU.USER_SEQ = TUA.USER_SEQ 
INNER JOIN TB_AUTH TA
ON TUA.AUTH_SEQ = TA.AUTH_SEQ 
LEFT JOIN TB_AUTH UTA
ON TA.UPPER_AUTH_SEQ = UTA.AUTH_SEQ 
WHERE TUAL.METHOD_SIGNATURE = 'findContents'
AND TUAL.METHOD_TYPE_NAME = 'GET'
AND TUAL.URL LIKE '%ASSET%' AND URL LIKE '%HO%'
# AND TUAL.URL LIKE '%TOOLKIT%'
# AND TUAL.URL LIKE '%FOUNDATION%'
AND TUAL.REGISTRATION_DT BETWEEN '2020-09-24 00:00:00' AND '2020-11-30 23:59:59'
# AND TUAL.DEVICE = 'PC'
# AND TUAL.DEVICE = 'MO'
) T
GROUP BY T.AUTH_SEQ
) S
ON TA.AUTH_SEQ = S.AUTH_SEQ
# WHERE TA.AUTH_DEPTH = 1
WHERE TA.AUTH_DEPTH = 2



SELECT 	TUAL.*
FROM TB_USER_ACTION_LOG TUAL
WHERE TUAL.METHOD_SIGNATURE = 'findContents'
  AND TUAL.METHOD_TYPE_NAME = 'GET'
AND TUAL.URL LIKE '%ASSET%'
# AND TUAL.URL LIKE '%TOOLKIT%'
#   AND TUAL.URL LIKE '%FOUNDATION%'
  AND TUAL.REGISTRATION_DT BETWEEN '2020-10-26 00:00:00' AND '2020-11-30 23:59:59'
ORDER BY TUAL.REGISTRATION_DT ASC
# AND TUAL.DEVICE = 'PC'
# AND TUAL.DEVICE = 'MO'


SELECT 	*
FROM TB_USER_ACTION_LOG TUAL
WHERE TUAL.METHOD_SIGNATURE = 'findContents'
  AND TUAL.METHOD_TYPE_NAME = 'GET'
  AND TUAL.URL LIKE '%ASSET%' AND URL LIKE '%HO%'
# AND TUAL.URL LIKE '%TOOLKIT%'
# AND TUAL.URL LIKE '%FOUNDATION%'
  AND TUAL.REGISTRATION_DT BETWEEN '2020-09-24 00:00:00' AND '2020-11-30 23:59:59'
ORDER BY TUAL.REGISTRATION_DT ASC

# AND TUAL.DEVICE = 'PC'
# AND TUAL.DEVICE = 'MO'





/*
 * start 
 * 2020-10-26 17:04:53
 * 
 * end 
 * 2020-11-10 09:43:50
 */

#
# SELECT * FROM TB_USER_ACTION_LOG TUAL
# WHERE TUAL.METHOD_SIGNATURE = 'findContents'
# AND TUAL.METHOD_TYPE_NAME = 'GET'


# 4976
SELECT COUNT(A.URL) AS COUNT
FROM (
SELECT 	*
FROM TB_USER_ACTION_LOG TUAL
WHERE TUAL.METHOD_SIGNATURE = 'findContents'
  AND TUAL.METHOD_TYPE_NAME = 'GET'
  AND TUAL.URL LIKE '%ASSET%' AND URL LIKE '%HO%'
# AND TUAL.URL LIKE '%TOOLKIT%'
# AND TUAL.URL LIKE '%FOUNDATION%'
  AND TUAL.REGISTRATION_DT BETWEEN '2020-09-24 00:00:00' AND '2020-11-30 23:59:59'
ORDER BY TUAL.REGISTRATION_DT ASC
# AND TUAL.DEVICE = 'PC'
# AND TUAL.DEVICE = 'MO'
# ORDER BY DATETE ASC
    ) A
