-- 일별 평균 방문수
SELECT DT.DATE
		, IFNULL(RESULT.SUM, 0) AS SUM
		, IFNULL(RESULT.COUNT, 0) AS COUNT
		, ROUND(IFNULL(RESULT.AVERAGE, 0), 1) AS AVERAGE
FROM (
	SELECT CONCAT('2020-', A) AS DATE
	FROM (
		SELECT '01' AS A
		UNION ALL SELECT '02' 
		UNION ALL SELECT '03' 
		UNION ALL SELECT '04' 
		UNION ALL SELECT '05' 
		UNION ALL SELECT '06' 
		UNION ALL SELECT '07' 
		UNION ALL SELECT '08' 
		UNION ALL SELECT '09'
		UNION ALL SELECT '10'
		UNION ALL SELECT '11'
		UNION ALL SELECT '12'
	) A
) DT
LEFT JOIN (
	SELECT T.DATE
			, SUM(T.COUNT) AS SUM
			, COUNT(T.DATE) AS COUNT
			, AVG(T.COUNT) AS AVERAGE
	FROM (
		SELECT DATE_FORMAT(USER.DATE, "%Y-%m") AS DATE
				, COUNT(USER.DATE) AS COUNT
		FROM (
			SELECT DATE_FORMAT(TULL.LOGIN_DT, "%Y-%m-%d") AS DATE
			FROM TB_USER_LOGIN_LOG TULL
			WHERE TULL.LOGIN_DT BETWEEN '2020-01-01 00:00:00' AND '2020-11-12 23:59:59'
			GROUP BY DATE_FORMAT(TULL.LOGIN_DT, "%Y-%m-%d"), TULL.USER_SEQ
		) USER
		GROUP BY USER.DATE
	) T
	GROUP BY T.DATE
) AS RESULT
ON DT.DATE = RESULT.DATE
;