-- 월별 주문수 
SELECT DT.DATE, IFNULL(RESULT.COUNT , 0) AS COUNT
FROM (
	SELECT CONCAT('2020-', A) AS DATE
	FROM (
		SELECT '01' AS A
		UNION ALL SELECT '02' 
		UNION ALL SELECT '03' 
		UNION ALL SELECT '04' 
		UNION ALL SELECT '05' 
		UNION ALL SELECT '06' 
		UNION ALL SELECT '07' 
		UNION ALL SELECT '08' 
		UNION ALL SELECT '09'
		UNION ALL SELECT '10'
		UNION ALL SELECT '11'
		UNION ALL SELECT '12'
	) AS A 
) DT
LEFT JOIN (
	SELECT T.DATE, COUNT(T.DATE) AS COUNT
	FROM (
	SELECT DATE_FORMAT(TOS.REGISTRATION_DT, "%Y-%m") AS DATE, REGISTER_SEQ FROM TB_ORDER TOS
	WHERE TOS.REGISTRATION_DT BETWEEN '2020-09-24' AND '2020-11-30'
	GROUP BY DATE_FORMAT(TOS.REGISTRATION_DT, "%Y-%m"), REGISTER_SEQ 
	) T
	GROUP BY T.DATE
) AS RESULT
ON DT.DATE = RESULT.DATE
;