-- 2뎁스 그룹의 하위 그룹의 수 
SELECT TA.AUTH_NAME, IFNULL(BTA.COUNT, 0)+1 AS COUNT
FROM TB_AUTH TA
LEFT JOIN
(
	SELECT UPPER_AUTH_SEQ, COUNT(UPPER_AUTH_SEQ) AS COUNT
	FROM TB_AUTH 
	WHERE AUTH_DEPTH = 3
	GROUP BY UPPER_AUTH_SEQ
) BTA
ON TA.AUTH_SEQ = BTA.UPPER_AUTH_SEQ
WHERE TA.AUTH_DEPTH = 2
ORDER BY TA.AUTH_SEQ ASC
;




SELECT * FROM TB_AUTH WHERE AUTH_NAME = 'DAEYEON';
SELECT * FROM TB_AUTH WHERE UPPER_AUTH_SEQ = 21;

SELECT * FROM TB_REPORT tr 
WHERE USE_YN = 'Y'
AND AUTH_SEQ IN (
21
,95
,96
,97
,98
);