### 오더 목록 조회
GET http://{{host}}/api/order/list?page=0&size=20&beginDt=2020-07-01&endDt=2020-07-02
Authorization: {{auth}}
Content-Type: application/json



### 오더 상세 조회
GET http://{{host}}/api/order/13
Authorization: {{auth}}
Content-Type: application/json

