### 오더_상품_목록 조회
GET http://{{host}}/api/order/product/{{category1code}}?exposureYn=Y
//Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5dGgiLCJleHAiOjE2MjMzOTk3NDR9.lFIO5YpBjTPRD0EMPXbe0przRpeTn9E12hlLJnQaOe-KSIOg0yF9LvDodsJs5O0pmkUES_tt2vNweyW0nh4uxA
Content-Type: application/json

### 오더_상품_상세 조회
GET http://{{host}}/api/order/product/{{category1code}}/{{goodsSeq}}
//Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5dGgiLCJleHAiOjE2MjMzOTk3NDR9.lFIO5YpBjTPRD0EMPXbe0przRpeTn9E12hlLJnQaOe-KSIOg0yF9LvDodsJs5O0pmkUES_tt2vNweyW0nh4uxA
Content-Type: application/json


### 오더_상품등록
 POST http://{{host}}/api/order/product/{{category1code}}?category2code=2&category3code=3&agencySeq=1&goodsName=goodsName&goodsDescription=디스크립션&size=xl&unitPrice=10000&minimumOrderQuantity=1000&exposureYn=Y&useYn=Y
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5dGgiLCJleHAiOjE2MjMzOTk3NDR9.lFIO5YpBjTPRD0EMPXbe0przRpeTn9E12hlLJnQaOe-KSIOg0yF9LvDodsJs5O0pmkUES_tt2vNweyW0nh4uxA
#Accept: application/json
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="originalImg";filename="D:/test/1.jpg"

< D:/test/1.jpg

--WebAppBoundary--
Content-Disposition: form-data; name="thumbnailImg";filename="D:/test/2.jpg"


< D:/test/2.jpg

### 오더_상품수정
 #PUT http://{{host}}/api/order/product/{{category1code}}?category2code=3&category3code=2&agencySeq=1&goodsName=상품이름만 수정&goodsDescription=상품설명수정&size=xl&unitPrice=10000&minimumOrderQuantity=10000&exposureYn=Y&useYn=Y&goodsSeq=4
PUT http://{{host}}/api/order/product/{{category1code}}?category2code=4&goodsName=상품이름만!!&goodsDescription=상품설명수정&exposureYn=N&useYn=Y&goodsSeq=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5dGgiLCJleHAiOjE2MjMzOTk3NDR9.lFIO5YpBjTPRD0EMPXbe0przRpeTn9E12hlLJnQaOe-KSIOg0yF9LvDodsJs5O0pmkUES_tt2vNweyW0nh4uxA
Accept: application/json
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="originalImg";filename="D:/test/1.jpg"

< D:/test/1.jpg

--WebAppBoundary--
Content-Disposition: form-data; name="thumbnailImg";filename="D:/test/2.jpg"


< D:/test/2.jpg


### 오더_상품 삭제
 #PUT http://{{host}}/api/order/product/{{category1code}}?category2code=3&category3code=2&agencySeq=1&goodsName=상품이름만 수정&goodsDescription=상품설명수정&size=xl&unitPrice=10000&minimumOrderQuantity=10000&exposureYn=Y&useYn=Y&goodsSeq=4
DELETE http://{{host}}/api/order/product/{{category1code}}/{{goodsSeq}}
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5dGgiLCJleHAiOjE2MjMzOTk3NDR9.lFIO5YpBjTPRD0EMPXbe0przRpeTn9E12hlLJnQaOe-KSIOg0yF9LvDodsJs5O0pmkUES_tt2vNweyW0nh4uxA
Accept: application/json
