<template>
    <div>
        123
        <div>
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
            main<br />
        </div>
    </div>
</template>
<script>
export default {
    name: 'MainPage',
    data() {
        return {};
    },
    methods: {},
};
</script>
<style scoped></style>
