-- ATF_그룹별_상세보기수 (3depth)
# SELECT TA.AUTH_NAME, IFNULL(S.COUNT, 0) AS COUNT
# FROM TB_AUTH TA
#          LEFT JOIN
#      (
#          SELECT T.AUTH_SEQ, COUNT(T.AUTH_SEQ) AS COUNT
#          FROM (
#                   SELECT CASE
#                         WHEN TA.AUTH_DEPTH = 1 THEN TA.AUTH_SEQ
#                         WHEN TA.AUTH_DEPTH = 2 THEN TA.AUTH_SEQ
#                         WHEN TA.AUTH_DEPTH = 3 THEN UTA.AUTH_SEQ
#                         END AS AUTH_SEQ
#                   FROM TB_USER_ACTION_LOG TUAL
#                    INNER JOIN TB_USER TU
#                               ON TUAL.USER_SEQ = TU.USER_SEQ
#                    INNER JOIN TB_USER_AUTH TUA
#                               ON TU.USER_SEQ = TUA.USER_SEQ
#                    INNER JOIN TB_AUTH TA
#                               ON TUA.AUTH_SEQ = TA.AUTH_SEQ
#                    LEFT JOIN TB_AUTH UTA
#                              ON TA.UPPER_AUTH_SEQ = UTA.AUTH_SEQ
#                   WHERE TUAL.METHOD_SIGNATURE = 'findContents'
#                     AND TUAL.METHOD_TYPE_NAME = 'GET'
#                     AND TUAL.URL LIKE '%ASSET%'
# #                     AND TUAL.URL LIKE '%TOOLKIT%'
# #                     AND TUAL.URL LIKE '%FOUNDATION%'
#                     AND TUAL.REGISTRATION_DT BETWEEN '2020-12-16 00:00:00' AND '2021-01-15 23:59:59'
# #                     AND TA.AUTH_DEPTH = 2
#                     AND TA.AUTH_DEPTH = 3
#              AND TUAL.DEVICE = 'PC'
#               ) T
#          GROUP BY T.AUTH_SEQ
#      ) S
#      ON TA.AUTH_SEQ = S.AUTH_SEQ
# WHERE TA.AUTH_DEPTH = 2
# ORDER BY TA.AUTH_SEQ
# ;

-- ATF_그룹별_상세보기수 (3depth)
SELECT TA.AUTH_NAME, IFNULL(S.COUNT, 0) AS COUNT
FROM TB_AUTH TA
LEFT JOIN
(
    SELECT T.AUTH_SEQ, COUNT(T.AUTH_SEQ) AS COUNT
    FROM (
        SELECT 	CASE
        WHEN TA.AUTH_DEPTH = 1 THEN TA.AUTH_SEQ
        WHEN TA.AUTH_DEPTH = 2 THEN TA.AUTH_SEQ
        WHEN TA.AUTH_DEPTH = 3 THEN UTA.AUTH_SEQ
        END AS AUTH_SEQ
        FROM TB_USER_ACTION_LOG TUAL
        INNER JOIN TB_USER TU
        ON TUAL.USER_SEQ = TU.USER_SEQ
        INNER JOIN TB_USER_AUTH TUA
        ON TU.USER_SEQ = TUA.USER_SEQ
        INNER JOIN TB_AUTH TA
        ON TUA.AUTH_SEQ = TA.AUTH_SEQ
        LEFT JOIN TB_AUTH UTA
        ON TA.UPPER_AUTH_SEQ = UTA.AUTH_SEQ
        WHERE TUAL.METHOD_SIGNATURE = 'findContents'
        AND TUAL.METHOD_TYPE_NAME = 'GET'
#           AND TUAL.URL LIKE '%ASSET%'
                    AND TUAL.URL LIKE '%TOOLKIT%'
#                     AND TUAL.URL LIKE '%FOUNDATION%'
#           AND TUAL.REGISTRATION_DT BETWEEN '2021-02-16 00:00:00' AND '2021-03-15 23:59:59'
          AND TUAL.REGISTRATION_DT BETWEEN '2021-03-16 00:00:00' AND '2021-04-15 23:59:59'
#           AND TUAL.DEVICE = 'PC'
#           AND TUAL.DEVICE = 'MO'
        AND TA.AUTH_DEPTH = 1
#         AND TA.AUTH_DEPTH = 3
    ) T
    GROUP BY T.AUTH_SEQ
) S
ON TA.AUTH_SEQ = S.AUTH_SEQ
WHERE TA.AUTH_DEPTH = 1
ORDER BY TA.AUTH_SEQ
;



# SELECT TA.AUTH_NAME, IFNULL(S.COUNT, 0) AS COUNT
# FROM TB_AUTH TA
# LEFT JOIN
# (
#     SELECT T.AUTH_SEQ, COUNT(T.AUTH_SEQ) AS COUNT
#     FROM (
#         SELECT 	CASE
#             WHEN TA.AUTH_DEPTH = 1 THEN TA.AUTH_SEQ
#             WHEN TA.AUTH_DEPTH = 2 THEN TA.AUTH_SEQ
#             WHEN TA.AUTH_DEPTH = 3 THEN UTA.AUTH_SEQ
#         END AS AUTH_SEQ
#         FROM TB_USER_ACTION_LOG TUAL
#         INNER JOIN TB_USER TU
#         ON TUAL.USER_SEQ = TU.USER_SEQ
#         INNER JOIN TB_USER_AUTH TUA
#         ON TU.USER_SEQ = TUA.USER_SEQ
#         INNER JOIN TB_AUTH TA
#         ON TUA.AUTH_SEQ = TA.AUTH_SEQ
#         LEFT JOIN TB_AUTH UTA
#         ON TA.UPPER_AUTH_SEQ = UTA.AUTH_SEQ
#         WHERE TUAL.METHOD_SIGNATURE = 'findContents'
#         AND TUAL.METHOD_TYPE_NAME = 'GET'
#         AND TUAL.URL LIKE '%ASSET%'
#         # AND TUAL.URL LIKE '%TOOLKIT%'
#         # AND TUAL.URL LIKE '%FOUNDATION%'
# #             AND TUAL.REGISTRATION_DT BETWEEN '2020-09-24 00:00:00' AND '2020-11-30 23:59:59'
#         AND TUAL.REGISTRATION_DT BETWEEN '2020-09-24 00:00:00' AND '2020-09-30 23:59:59'
# #         AND TUAL.REGISTRATION_DT BETWEEN '2020-10-01 00:00:00' AND '2020-10-31 23:59:59'
# #         AND TUAL.REGISTRATION_DT BETWEEN '2020-11-01 00:00:00' AND '2020-11-30 23:59:59'
# #         AND UTA.AUTH_DEPTH = 3
#         # AND TUAL.DEVICE = 'PC'
#         # AND TUAL.DEVICE = 'MO'
#     ) T
#     GROUP BY T.AUTH_SEQ
# ) S
# ON TA.AUTH_SEQ = S.AUTH_SEQ
# # WHERE TA.AUTH_DEPTH = 1
# WHERE TA.AUTH_DEPTH = 2
# ORDER BY TA.AUTH_SEQ;








/*
 * start 
 * 2020-10-26 17:04:53
 * 
 * end 
 * 2020-11-10 09:43:50
 */


SELECT 	TUAL.*
FROM TB_USER_ACTION_LOG TUAL
         INNER JOIN TB_USER TU
                    ON TUAL.USER_SEQ = TU.USER_SEQ
         INNER JOIN TB_USER_AUTH TUA
                    ON TU.USER_SEQ = TUA.USER_SEQ
         INNER JOIN TB_AUTH TA
                    ON TUA.AUTH_SEQ = TA.AUTH_SEQ
         LEFT JOIN TB_AUTH UTA
                   ON TA.UPPER_AUTH_SEQ = UTA.AUTH_SEQ
WHERE TUAL.METHOD_SIGNATURE = 'findContents'
  AND TUAL.METHOD_TYPE_NAME = 'GET'
#   AND TUAL.URL LIKE '%ASSET%'
  AND TUAL.REGISTRATION_DT BETWEEN '2020-01-01 00:00:00' AND '2020-11-12 23:59:59'
ORDER BY TUAL.REGISTRATION_DT ASC
;



SELECT *
FROM TB_CONTENTS
WHERE REGISTRATION_DT BETWEEN '2020-10-26 00:00:00' AND '2020-12-15 23:59:59'
AND TOP_MENU_CODE = 'TOOLKIT';

SELECT *
FROM TB_CONTENTS
WHERE FOLDER_NAME = 'HO20_컨수머 마인드셋 스타일링 비디오 가이드'
;


SELECT COUNT(*)
        FROM TB_USER_ACTION_LOG TUAL
        INNER JOIN TB_USER TU
        ON TUAL.USER_SEQ = TU.USER_SEQ
        INNER JOIN TB_USER_AUTH TUA
        ON TU.USER_SEQ = TUA.USER_SEQ
        INNER JOIN TB_AUTH TA
        ON TUA.AUTH_SEQ = TA.AUTH_SEQ
        LEFT JOIN TB_AUTH UTA
        ON TA.UPPER_AUTH_SEQ = UTA.AUTH_SEQ
        WHERE TUAL.METHOD_SIGNATURE = 'findContents'
        AND TUAL.METHOD_TYPE_NAME = 'GET'
          AND TUAL.URL LIKE '%ASSET%'
#                     AND TUAL.URL LIKE '%TOOLKIT%'
#                     AND TUAL.URL LIKE '%FOUNDATION%'
#           AND TUAL.REGISTRATION_DT BETWEEN '2020-12-16 00:00:00' AND '2021-01-15 23:59:59'
          AND TUAL.REGISTRATION_DT BETWEEN '2021-01-16 00:00:00' AND '2021-02-15 23:59:59'
#           AND TUAL.DEVICE = 'PC'
#           AND TUAL.DEVICE = 'MO'
#         AND TA.AUTH_DEPTH = 2