SELECT *
FROM TB_AUTH
WHERE AUTH_NAME = 'KU & HOOPS';



SELECT *
FROM TB_AUTH
WHERE AUTH_SEQ = 28
   OR UPPER_AUTH_SEQ = 28
#    OR UPPER_AUTH_SEQ = 112 OR UPPER_AUTH_SEQ = 113
;





# 되는쿼리
-- ASSET 게시물별 다운로드 수
-- TOOLKIT 게시물별 다운로드 수
-- FOUNDATION 게시물별 다운로드 수
SELECT tc.FOLDER_NAME
      , SUM(CASE
#                 WHEN T.REGISTRATION_DT BETWEEN '2020-12-16 00:00:00' AND '2021-01-15 23:59:59' THEN 1
#                 WHEN T.REGISTRATION_DT BETWEEN '2021-01-16 00:00:00' AND '2021-02-15 23:59:59' THEN 1
                WHEN T.REGISTRATION_DT BETWEEN '2021-02-16 00:00:00' AND '2021-03-15 23:59:59' THEN 1
                ELSE 0
        END) 'DEC'
 FROM TB_CONTENTS tc
LEFT JOIN (
     SELECT TCF.CONTENTS_SEQ, TDL.REGISTRATION_DT
     FROM TB_DOWNLOAD_LOG TDL
              INNER JOIN TB_CONTENTS_FILE TCF
                         ON TDL.FILE_SEQ = TCF.CONTENTS_FILE_SEQ
              INNER JOIN TB_USER TU
                         ON TDL.REGISTER_SEQ = TU.USER_SEQ
              INNER JOIN TB_USER_AUTH TUA
                         ON TU.USER_SEQ = TUA.USER_SEQ
              INNER JOIN TB_AUTH TA
                         ON TUA.AUTH_SEQ = TA.AUTH_SEQ
     WHERE TDL.DOWNLOAD_TYPE = 'CONTENTS'
#        AND TDL.REGISTRATION_DT BETWEEN '2020-12-16 00:00:00' AND '2021-01-15 23:59:59'
#        AND TDL.REGISTRATION_DT BETWEEN '2021-01-16 00:00:00' AND '2021-02-15 23:59:59'
       AND TDL.REGISTRATION_DT BETWEEN '2021-02-16 00:00:00' AND '2021-03-15 23:59:59'
        -- DAEYEON
#             AND (TA.AUTH_SEQ = 21 OR TA.UPPER_AUTH_SEQ = 21 OR TA.AUTH_SEQ = 95 OR TA.AUTH_SEQ = 96 OR TA.AUTH_SEQ = 97 OR TA.AUTH_SEQ = 98)
        -- WINWIN SPORTS
#             AND (TA.AUTH_SEQ = 22 OR TA.UPPER_AUTH_SEQ = 22 OR TA.AUTH_SEQ = 99 OR TA.AUTH_SEQ = 100 OR TA.AUTH_SEQ = 101 OR TA.AUTH_SEQ = 102)
        -- EUNGWANG
#             AND (TA.AUTH_SEQ = 23 OR TA.UPPER_AUTH_SEQ = 23 OR TA.AUTH_SEQ = 103 OR TA.AUTH_SEQ = 104 OR TA.AUTH_SEQ = 105)
        -- SHOE LAND
#             AND (TA.AUTH_SEQ = 24 OR TA.UPPER_AUTH_SEQ = 24 OR TA.AUTH_SEQ = 106 OR TA.AUTH_SEQ = 107)
        -- HD
#             AND (TA.AUTH_SEQ = 25 OR TA.UPPER_AUTH_SEQ = 25 OR TA.AUTH_SEQ = 108 OR TA.AUTH_SEQ = 109)
        -- DAESAN SPORTS
#             AND (TA.AUTH_SEQ = 26 OR TA.UPPER_AUTH_SEQ = 26 OR TA.AUTH_SEQ = 110 OR TA.AUTH_SEQ = 111)
       -- SMH SPORTS KOREA
#             AND (TA.AUTH_SEQ = 27 OR TA.UPPER_AUTH_SEQ = 27 OR TA.AUTH_SEQ = 112 OR TA.AUTH_SEQ = 113)
        -- KU & HOOPS
            AND (TA.AUTH_SEQ = 28 OR TA.UPPER_AUTH_SEQ = 28 OR TA.AUTH_SEQ = 114 OR TA.AUTH_SEQ = 115)
 ) T

ON T.CONTENTS_SEQ = tc.CONTENTS_SEQ
WHERE tc.TOP_MENU_CODE = 'ASSET'
# AND tc.REGISTRATION_DT BETWEEN '2020-12-16 00:00:00' AND '2021-01-15 23:59:59'
# AND tc.REGISTRATION_DT BETWEEN '2021-01-16 00:00:00' AND '2021-02-15 23:59:59'
AND tc.REGISTRATION_DT BETWEEN '2021-02-16 00:00:00' AND '2021-03-15 23:59:59'
# WHERE tc.TOP_MENU_CODE = 'TOOLKIT'
# WHERE tc.TOP_MENU_CODE = 'FOUNDATION'
 GROUP BY tc.CONTENTS_SEQ
;






-- 조합중
# SELECT TCF.CONTENTS_SEQ, TDL.REGISTRATION_DT
# FROM TB_DOWNLOAD_LOG TDL
#     INNER JOIN TB_CONTENTS_FILE TCF
#             ON TDL.FILE_SEQ = TCF.CONTENTS_FILE_SEQ
#     INNER JOIN TB_USER TU
#             ON TDL.REGISTER_SEQ = TU.USER_SEQ
#     INNER JOIN TB_USER_AUTH TUA
#             ON TU.USER_SEQ = TUA.USER_SEQ
#     INNER JOIN TB_AUTH TA
#             ON TUA.AUTH_SEQ = TA.AUTH_SEQ
# WHERE TDL.DOWNLOAD_TYPE = 'CONTENTS'
#     AND TDL.REGISTRATION_DT BETWEEN '2020-11-16 00:00:00' AND '2020-12-15 23:59:59'
#     AND (TA.AUTH_SEQ = 21 OR TA.UPPER_AUTH_SEQ = 21 OR TA.UPPER_AUTH_SEQ = 95 OR TA.UPPER_AUTH_SEQ = 96 OR TA.UPPER_AUTH_SEQ = 97 OR TA.UPPER_AUTH_SEQ = 98)
# ;
#
#
#
#
#
# # 다운로드 테이블 (배열로 요청하면 하나하나 쌓임)
# SELECT TA.AUTH_NAME, IFNULL(S.COUNT, 0) AS COUNT
# FROM TB_AUTH TA
#          LEFT JOIN
#      (
#          SELECT T.AUTH_SEQ, COUNT(T.AUTH_SEQ) AS COUNT
#          FROM (
#                   SELECT CASE
#                     WHEN TA.AUTH_DEPTH = 1 THEN TA.AUTH_SEQ
#                     WHEN TA.AUTH_DEPTH = 2 THEN TA.AUTH_SEQ
#                     WHEN TA.AUTH_DEPTH = 3 THEN UTA.AUTH_SEQ
#                     END AS AUTH_SEQ
#                   FROM TB_DOWNLOAD_LOG TDL
#                    INNER JOIN TB_USER TU
#                               ON TDL.REGISTER_SEQ = TU.USER_SEQ
#                    INNER JOIN TB_USER_AUTH TUA
#                               ON TU.USER_SEQ = TUA.USER_SEQ
#                    INNER JOIN TB_AUTH TA
#                               ON TUA.AUTH_SEQ = TA.AUTH_SEQ
#                    LEFT JOIN TB_AUTH UTA
#                              ON TA.UPPER_AUTH_SEQ = UTA.AUTH_SEQ
#                    LEFT JOIN TB_CONTENTS_FILE TCF
#                              ON TDL.FILE_SEQ = TCF.CONTENTS_FILE_SEQ
#                    LEFT JOIN TB_CONTENTS TC
#                              ON TCF.CONTENTS_SEQ = TC.CONTENTS_SEQ
#                   WHERE TDL.DOWNLOAD_TYPE = 'CONTENTS'
#                     AND TC.TOP_MENU_CODE = 'ASSET'
#                     AND TDL.REGISTRATION_DT BETWEEN '2020-11-16 00:00:00' AND '2020-12-15 23:59:59'
#                     AND TA.AUTH_SEQ = 21 OR TA.UPPER_AUTH_SEQ = 21 OR TA.UPPER_AUTH_SEQ = 95 OR TA.UPPER_AUTH_SEQ = 96 OR TA.UPPER_AUTH_SEQ = 97 OR TA.UPPER_AUTH_SEQ = 98
#               ) T
#          GROUP BY T.AUTH_SEQ
#      ) S
#      ON TA.AUTH_SEQ = S.AUTH_SEQ
# WHERE TA.AUTH_DEPTH = 2
# ORDER BY TA.AUTH_SEQ;
#
#
#
# SELECT CASE
#            WHEN TA.AUTH_DEPTH = 1 THEN TA.AUTH_SEQ
#            WHEN TA.AUTH_DEPTH = 2 THEN TA.AUTH_SEQ
#            WHEN TA.AUTH_DEPTH = 3 THEN UTA.AUTH_SEQ
#            END AS AUTH_SEQ
#             , TA.*
# FROM TB_DOWNLOAD_LOG TDL
#          INNER JOIN TB_USER TU
#                     ON TDL.REGISTER_SEQ = TU.USER_SEQ
#          INNER JOIN TB_USER_AUTH TUA
#                     ON TU.USER_SEQ = TUA.USER_SEQ
#          INNER JOIN TB_AUTH TA
#                     ON TUA.AUTH_SEQ = TA.AUTH_SEQ
#          LEFT JOIN TB_AUTH UTA
#                    ON TA.UPPER_AUTH_SEQ = UTA.AUTH_SEQ
#          LEFT JOIN TB_CONTENTS_FILE TCF
#                    ON TDL.FILE_SEQ = TCF.CONTENTS_FILE_SEQ
#          LEFT JOIN TB_CONTENTS TC
#                    ON TCF.CONTENTS_SEQ = TC.CONTENTS_SEQ
# WHERE TDL.DOWNLOAD_TYPE = 'CONTENTS'
#   AND TC.TOP_MENU_CODE = 'ASSET'
#   AND TDL.REGISTRATION_DT BETWEEN '2020-11-16 00:00:00' AND '2020-12-15 23:59:59'
#   AND TA.AUTH_SEQ = 21 OR TA.UPPER_AUTH_SEQ = 21 OR TA.UPPER_AUTH_SEQ = 95 OR TA.UPPER_AUTH_SEQ = 96 OR TA.UPPER_AUTH_SEQ = 97 OR TA.UPPER_AUTH_SEQ = 98
# ;
#
#
#
#

